name: inpick-fastapi
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - pandas>=2.1
  - pytorch>=2.6
  - cpuonly
  - mkl
  - mkl-service
  - scikit-learn
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - pydantic-settings
      - python-multipart
      - requests
      - gunicorn
      - motor
      - python-dotenv
      - langchain
      - langchain-openai
      - langchain-google-genai
      - langchain-anthropic
      - openai
      - openpyxl
      - crewai
      - crewai[tools]
      - psycopg2-binary
      - asyncpg
      - databases
      - sqlalchemy
      - faiss-cpu
      - huggingface-hub
      - implicit
